---

include:
  - local: '/template/prepare_vm.yml'

variables:
  BUILD_SCRIPT: ./.gitlab/ci/build_releng.sh
  PACKAGE_LIST: archiso erofs-utils openssl zsync
  QEMU_BUILD_TIMEOUT: 2400
  QEMU_VM_MEMORY: 3072
  ARCHISO_COW_SPACE_SIZE: 2g

stages:
  - check
  - build

shellcheck:
  before_script:
    - pacman --noconfirm -Syu --needed make shellcheck
  script:
    - make check
  stage: check

build:
  after_script:
    - mv -- output/metrics.txt .
  except:
    - master@archlinux/releng
    - schedules@archlinux/releng
    - tags@archlinux/releng
  extends: .build
  tags:
    - fast-single-thread

secure_build:
  after_script:
    - mv -- "output/metrics.txt" .
  extends: .build
  only:
    - master@archlinux/releng
    - schedules@archlinux/releng
    - tags@archlinux/releng
  tags:
    - secure
